#!/bin/bash -l

echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "=========================================================="


module load python2/2.7.16

PATH={COMMON_SCRIPT_DIR}:$PATH

# now do the main process: 
RAW_DIR={PROJECT_RAWDATA_DIR} #Raw seq location  
DIR={PROJECT_DIR}  # yun's working project location

FASTQ_DIR=${DIR}/FASTQ

# if FASTQ_DIR not yet exists
# call the script to create the directory and link the fastq files
# to it: 
if [ ! -d $FASTQ_DIR ] 
then  
    CMD="{FILEMAP_SCRIPT} $RAW_DIR $FASTQ_DIR"
    echo $CMD
    eval $CMD
else
    echo "$FASTQ_DIR exists already!"
fi


echo "=========================================================="
echo "Finished on : $(date)"
echo "=========================================================="
