#!/bin/bash -l

# this file serving as template for creating customized qsub file, 
# the file name shall be changed properly after customized for job.
# run 'qsub [-N jobname] myjobname.qsub projectname'
#
# All lines starting with "#" are comments
# All lines starting with "#$" are SGE qsub commands
# 

#  Specify a project to use (Required for BUMC projects).
#$ -P tcwlab

#  Give this job a name
#$ -N aRNASeq_{PROJECTNAME}_fastqc

#  Join standard output and error to a single file
#$ -j y #could be 'n' if not to merge error and output

#  Name the log directory where to redirect standard output and error
#$ -o ../qlog/fqc # make sure qlog/ exists and is in the working directory, otherwise give the full path.

#  request enough memory:
#$ -l mem_per_core=4G

# Specify computing resources
# can be omp, 
##$ -pe omp 8 

# distributing all the fastq files to 20 tasks
#$ -t 1-{SGE_TOTAL_TASK} #40 

# Now let's keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "Task index number : $SGE_TASK_ID"
echo "Total task number : $SGE_TASK_LAST"
echo "=========================================================="


# Load any modules you might want to use.
module load python2/2.7.16

PATH={COMMON_SCRIPT_DIR}:$PATH

# now do the main process: 
#RAW_DIR={PROJECT_RAWDATA_DIR} #Raw seq location  
#YUN_DIR={PROJECT_DIR}  # yun's working project location

FASTQ_DIR={PROJECT_DIR}/FASTQ
FASTQC_OUTDIR={PROJECT_DIR}/FASTQC

# if FASTQC_INDIR not yet exists
# call the script to create the directory and link the fastq files
# to it: 
if [ ! -d $FASTQ_DIR ]
then 
    echo "$FASTQ_DIR doesn't exist. Please link the fastq files first!"
    exit
fi

# now call FASTQC:
module load fastqc/0.11.7

mkdir -p $FASTQC_OUTDIR
CMD="task_distrib.pl $FASTQ_DIR $SGE_TASK_LAST $SGE_TASK_ID"
echo $CMD
fq_list=`eval $CMD`
echo "fastq files to be processed by this batch #$SGE_TASK_ID :"
for fq in ${fq_list[@]}
do
    echo $fq
done
echo "++++++++++++++++++"

for fq in `eval $CMD`
do
    echo "Now process $FASTQ_DIR/$fq"
    CMD="fastqc -f fastq -o $FASTQC_OUTDIR  $FASTQ_DIR/$fq"
    echo $CMD
    eval $CMD
done

echo "=========================================================="
echo "Finished on : $(date)"
echo "=========================================================="
