#!/bin/bash -l


echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "=========================================================="


# Load any modules you might want to use.
#module load python2/2.7.16
# load module first
module load python3/3.7.9
module load multiqc/1.10.1

PATH={COMMON_SCRIPT_DIR}:$PATH

DIR={PROJECT_DIR}

FASTQ_DIR=${DIR}/FASTQ/
MULTIQC_INDIR=${DIR}/FASTQC
MULTIQC_OUTDIR=${DIR}/MULTIQC
mkdir -p $MULTIQC_OUTDIR

total_file_count=`ls $FASTQ_DIR/*.fastq.gz |wc -l` # this is the expected number of qc files to process
echo "TOTAL FASTQ File Count=$total_file_count"

# check if fastqc result is already generated or not
if [ ! -d $MULTIQC_INDIR ] 
then  
    echo "It seems STEP1 - fastqc hasn't been run. There is no $MULTIQC_INDIR folder. "
    exit
else 
    fqc_file_count=`ls $MULTIQC_INDIR/*.zip |wc -l`
    echo "TOTAL FASTQC File Count=$fqc_file_count"

    # if [ $fqc_file_count -ne $total_file_count ] 
    # then
    # 	echo "It seems STEP1 - fastqc hasn't been completed for all input fastq sequence files."
    # 	echo "Please go to $FASTQC_INDIR and check. "
    #     echo "You can submit job with dependency control:"
    #     echo "  qsub -hold_jid aRNASeq_{PROJECTNAME}_fastqc RNASeq_{PROJECTNAME}_multiqc"
    # 	exit
    # fi
fi


# now call MULTIQC:

mkdir -p $MULTIQC_OUTDIR
cd $MULTIQC_OUTDIR
echo "Entered $MULTI_OUTDIR and run multiqc ..."
multiqc $MULTIQC_INDIR 
echo "Finished multiqc"

echo "=========================================================="
echo "Finished on : $(date)"
echo "=========================================================="
