#!/bin/bash -l

echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "=========================================================="


# Load any modules you might want to use.
#module load python2/2.7.16
# load module first
module purge
module load python3/3.7.9
module load multiqc/1.10.1

PATH={COMMON_SCRIPT_DIR}:$PATH


PROJ_DIR={PROJECT_DIR}

MULTIQC_INDIR=${PROJ_DIR}/Alignment
MULTIQC_OUTDIR=${PROJ_DIR}/MULTIQC_ALN
mkdir -p $MULTIQC_OUTDIR


# now call MULTIQC:

mkdir -p $MULTIQC_OUTDIR
cd $MULTIQC_OUTDIR
echo "Entered $MULTI_OUTDIR and run multiqc ..."
multiqc $MULTIQC_INDIR 
echo "Finished multiqc for $MULTIQC_INDIR and results are in $MULTIQC_OUTDIR"

echo "=========================================================="
echo "Finished on : $(date)"
echo "=========================================================="
