#!/bin/bash -l

echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "Task index number : $SGE_TASK_ID"
echo "Total task number : $SGE_TASK_LAST"
echo "=========================================================="


# Load any modules you might want to use.

# load star:
#module load star/2.5.3a  #SCC doesn't have the specific version
module load samtools


GENOME_DIR=/RawData/Genome2.7.9a/hg38/

PROJ_DIR={PROJECT_DIR}

FASTQ_DIR=${PROJ_DIR}/FASTQ/
BAM_DIR=${PROJ_DIR}/Alignment/

total_fq=$((`wc -l < $FASTQ_DIR/sample_map.csv`-1))
sample_name_list=$FASTQ_DIR/sample_treatment_list.csv
total_sample=`wc -l < $sample_name_list`
echo "There are $total_fq files under $FASTQ_DIR and they represent $total_sample samples"

sample_batch=`task_distrib.pl $sample_name_list $SGE_TASK_LAST $SGE_TASK_ID`

cd $BAM_DIR
for sample in ${sample_batch[@]}
do
    bam=${sample}Aligned.sortedByCoord.out.bam
    bai=${bam}.bai
    echo "Indexing $bam ..."
    CMD="samtools index $bam $bai " 
    echo $CMD
    eval $CMD
done
echo "++++++++++++++++++"

echo "=========================================================="
echo "Finished JOB #$JOB_ID Batch #$SGE_TASK_ID on : $(date)"
echo "=========================================================="
