#!/bin/bash -l

# this file serving as template for creating customized qsub file, 
# the file name shall be changed properly after customized for job.
# run 'qsub myjobname.qsub'
#
# All lines starting with "#" are comments
# All lines starting with "#$" are SGE qsub commands
# 

#  Specify a project to use (Required for BUMC projects).
#$ -P tcwlab

#  Give this job a name
#$ -N aRNASeq_{PROJECTNAME}_idx_bam

#  Join standard output and error to a single file
#$ -j y #could be 'n' if not to merge error and output

#  Name the log directory where to redirect standard output and error
#$ -o ../qlog/idx_bam # make sure qlog/ exists and is in the working directory, otherwise give the full path.

#  request enough memory:
# 4G is too small, job got killed
# try 8G
#$ -l mem_per_core=8G  

# Specify computing resources
# can be omp, 
#$ -pe omp 8 

# distributing all the fastq files to 20 tasks
#$ -t 1-{SGE_TOTAL_TASK}  #40 

# Now let's keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "Task index number : $SGE_TASK_ID"
echo "Total task number : $SGE_TASK_LAST"
echo "=========================================================="


# Load any modules you might want to use.

# load star:
#module load star/2.5.3a  #SCC doesn't have the specific version
module load samtools

# add executable path:
#COMMON_SCRIPT_DIR=/projectnb/tcwlab/yshen16/Project/scripts
PATH={COMMON_SCRIPT_DIR}:$PATH

# set up the general environ. vars: 
TCWLAB_ROOT=/projectnb/tcwlab/
# use the newly generated genome index:
GENOME_DIR=${TCWLAB_ROOT}/RawData/Genome2.7.9a/hg38/

# now do the main process: 
#RAW_DIR=/projectnb/tcwlab/RawRNAseq/IsogenicAPOE/wpoon228 #Raw seq location
#JULIA_DIR=/projectnb/tcwlab/Project/IsogenicAPOE/  # orig. project location
PROJ_DIR={PROJECT_DIR} #/projectnb/tcwlab/yshen16/Project/IsogenicAPOE/  # yun's working project location
#cd /projectnb/tcwlab/yshen16/JuliaNote # copied JuliaNote for reference

FASTQ_DIR=${PROJ_DIR}/FASTQ/
BAM_DIR=${PROJ_DIR}/Alignment/

total_fq=$((`wc -l < $FASTQ_DIR/sample_map.csv`-1))
sample_name_list=$FASTQ_DIR/sample_treatment_list.csv
total_sample=`wc -l < $sample_name_list`
echo "There are $total_fq files under $FASTQ_DIR and they represent $total_sample samples"

sample_batch=`task_distrib.pl $sample_name_list $SGE_TASK_LAST $SGE_TASK_ID`

cd $BAM_DIR
for sample in ${sample_batch[@]}
do
    bam=${sample}Aligned.sortedByCoord.out.bam
    bai=${bam}.bai
    echo "Indexing $bam ..."
    CMD="samtools index $bam $bai " 
    echo $CMD
    eval $CMD
done
echo "++++++++++++++++++"

echo "=========================================================="
echo "Finished JOB #$JOB_ID Batch #$SGE_TASK_ID on : $(date)"
echo "=========================================================="
