#!/bin/bash -l

# this file serving as template for creating customized qsub file, 
# the file name shall be changed properly after customized for job.
# run 'qsub myjobname.qsub'
#
# All lines starting with "#" are comments
# All lines starting with "#$" are SGE qsub commands
# 

#  Specify a project to use (Required for BUMC projects).
#$ -P tcwlab

#  Give this job a name
#$ -N RNASeq_{PROJECTNAME}_fc

#  Join standard output and error to a single file
#$ -j y #could be 'n' if not to merge error and output

#  Name the log directory where to redirect standard output and error
#$ -o ../qlog/fc # make sure qlog/ exists and is in the working directory, otherwise give the full path.

#  request enough memory:
# 4G is too small, job got killed
# try 8G
#$ -l mem_per_core=8G  

# Specify computing resources
# can be omp, 
#$ -pe omp 8 

# Now let's keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "=========================================================="


# Load any modules you might want to use.

# load module(s):
module load subread/1.6.2

# add executable path:
PATH={COMMON_SCRIPT_DIR}:$PATH

# set up the general environ. vars: 
TCWLAB_ROOT=/projectnb/tcwlab/
# use the newly generated genome index:
GENOME_DIR=${TCWLAB_ROOT}/RawData/Genome2.7.9a/hg38/

# now do the main process: 
#RAW_DIR=/projectnb/tcwlab/RawRNAseq/IsogenicAPOE/wpoon228 #Raw seq location
#JULIA_DIR=/projectnb/tcwlab/Project/IsogenicAPOE/  # orig. project location
PROJ_DIR={PROJECT_DIR} #/projectnb/tcwlab/yshen16/Project/IsogenicAPOE/  # yun's working project location
#cd /projectnb/tcwlab/yshen16/JuliaNote # copied JuliaNote for reference

FASTQ_DIR=${PROJ_DIR}/FASTQ/
BAM_DIR=${PROJ_DIR}/Alignment/
FC_DIR=${PROJ_DIR}/FeatureCount/
mkdir -p $FC_DIR

total_fq=$((`wc -l < $FASTQ_DIR/sample_map.csv`-1))
sample_name_list=$FASTQ_DIR/sample_treatment_list.csv
total_sample=`wc -l < $sample_name_list`
echo "There are $total_fq files under $FASTQ_DIR and they represent $total_sample samples"

cd $FC_DIR
echo "Do feature counting for $BAM_DIR ..."
# save the bam list for later reference:
BAM_FILELIST=${BAM_DIR}/ordered_bam_files.txt
BAM_POSTFIX=Aligned.sortedByCoord.out.bam
# make sure the fc output is in right order:
sed s:$:$BAM_POSTFIX: $sample_name_list | sed s:^:$BAM_DIR/: > $BAM_FILELIST #make sure include full path
FC_OUT=featureCounts.txt
FC_CLEAN=featureCounts_clean.txt

# original example: 
#featureCounts -t exon -g gene_id -a ${GENOME_DIR}/gencode.v26.annotation.gtf -o featureCounts.txt ${BAM_DIR}/*Aligned.sortedByCoord.out.bam
# new:
cat $BAM_FILELIST |xargs featureCounts -t exon -g gene_id -a ${GENOME_DIR}/gencode.v26.annotation.gtf -o $FC_OUT

echo "++++++++++++++++++"
echo "Done with running featureCounts"
echo "Clean the featureCounts.txt - removing column 2-6 and the 1st line ..."
perl -lane "splice @F, 1, 5; print join \"\\t\", @F if $.>1" $FC_OUT > $FC_CLEAN
echo "clean up the headline:"
sed -i "1s://:/:g" $FC_CLEAN
sed -i "1s:$BAM_DIR::g" $FC_CLEAN
sed -i "1s:$BAM_POSTFIX::g" $FC_CLEAN

echo "cleaned featureCount file: ${FC_DIR}/featureCounts_clean.txt"
echo "++++++++++++++++++"

echo "=========================================================="
echo "Finished JOB #$JOB_ID on : $(date)"
echo "=========================================================="
