#!/bin/bash -l

# this file serving as template for creating customized qsub file, 
# the file name shall be changed properly after customized for job.
# run 'qsub myjobname.qsub'
#
# All lines starting with "#" are comments
# All lines starting with "#$" are SGE qsub commands
# 

#  Specify a project to use (Required for BUMC projects).
#$ -P tcwlab

#  Give this job a name
#$ -N RNASeq_{PROJECTNAME}_mqc_aln

#  Join standard output and error to a single file
#$ -j y #could be 'n' if not to merge error and output

#  Name the log directory where to redirect standard output and error
#$ -o ../qlog/mqc_aln # make sure qlog_mqc_aln/ exists and is in the working directory, otherwise give the full path.

#  request enough memory:
#$ -l mem_per_core=4G

# Specify computing resources
# can be omp, 
##$ -pe omp 8 

# distributing all the fastq files to 20 tasks
##$ -t 1-40 

# Now let's keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "=========================================================="


# Load any modules you might want to use.
#module load python2/2.7.16
# load module first
module purge
module load python3/3.7.9
module load multiqc/1.10.1

#COMMON_SCRIPT_DIR=/projectnb/tcwlab/yshen16/Project/scripts
PATH={COMMON_SCRIPT_DIR}:$PATH


# now do the main process: 
#RAW_DIR=/projectnb/tcwlab/RawRNAseq/IsogenicAPOE/wpoon228 #Raw seq location
#JULIA_DIR=/projectnb/tcwlab/Project/IsogenicAPOE/  # orig. project location
PROJ_DIR={PROJECT_DIR} #/projectnb/tcwlab/yshen16/Project/IsogenicAPOE/  # yun's working project location
#cd /projectnb/tcwlab/yshen16/JuliaNote # copied JuliaNote for reference

MULTIQC_INDIR=${PROJ_DIR}/Alignment
MULTIQC_OUTDIR=${PROJ_DIR}/MULTIQC_ALN
mkdir -p $MULTIQC_OUTDIR


# now call MULTIQC:

mkdir -p $MULTIQC_OUTDIR
cd $MULTIQC_OUTDIR
echo "Entered $MULTI_OUTDIR and run multiqc ..."
multiqc $MULTIQC_INDIR 
echo "Finished multiqc for $MULTIQC_INDIR and results are in $MULTIQC_OUTDIR"

echo "=========================================================="
echo "Finished on : $(date)"
echo "=========================================================="
