# .github/workflows/r-ci.yml
name: R CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  Test:
    runs-on: ubuntu-latest  

    steps:
      - name: Check repo
        uses: actions/checkout@v2 

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('ggplot2', 'dplyr', 'tidyr', 'reshape2', 'data.table',
                              'fgsea', 'ggvenn', 'igraph', 'ggraph', 'stringr',
                              'ComplexHeatmap', 'RColorBrewer', 'pheatmap', 'tibble',
                              'ggplotify', 'ggrepel', 'ggfortify', 'rlang',
                              'WGCNA', 'DESeq2', 'sva', 'GSA', 'car', 'bestNormalize'))"
      
      - name: Run R Scripts
        run: |
          for script in /georgewu25/Script/*.R; do
            Rscript "$script"
          done

      - name: Check R code validity
        run: |
          Rscript -e 'lintr::lint_package()'
